# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITCC Practicle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITCC Practicle
    pod 'Alamofire', '~> 5.4'
    pod 'IQKeyboardManagerSwift'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'DropDown', '2.3.2'
end
